### ISSUE TITLE
More fun.

### ISSUE THREAD

**Issue by pixxon** [pixxon/project-tools#13]
Any ideas, to improve the Version 1.0 for better gameplay.

**Comment by ordogfioka** [comment]
Users should be able to create different rooms

**Comment by ordogfioka** [comment]
Any user should be able to give his username

**Comment by ordogfioka** [comment]
Any user should be able customize his character

**Comment by ordogfioka** [comment]
Different kind of bombs
For example: 2 or more bombs at the same time, bomb explosion bind to the user interaction

**Comment by pixxon** [comment]
Due to lack of time the project will not be continued.
